### ISSUE TITLE
issue to make text on badge

### ISSUE THREAD

**Issue by azze-r** [kiwisip/BadgeControl#5]
Hello, when i try this instruction as i see on the readme :

`self.badge!.addOrReplaceCurrent(with text: "5", animated: true)
`

produces an error -> "Expected ',' separator" :

And when i try to fix it so no error is showed with this line :

`self.badge!.addOrReplaceCurrent(with : "5", animated: true)
`

I don't see any text on the badge

**Comment by rkrenecky** [comment]
Hello! 
First of all thanks for pointing out the mistake in documentation, I'll fix that. Your second problem - I have no idea why does it not work for you. Please check the example project that is provided with this library - everything works fine there.

**Comment by azze-r** [comment]
Thanks for reply, my code is juste the same as the documentation with one exception, i'm working on top of UIButton, and on the project you're using UIImageView, u think the library is compatible with UIButton ?

**Comment by rkrenecky** [comment]
I don't see a reason why it should not work with `UIButton` - I tried replacing the `UIImageView` with `UIButton` in the sample project and everything works fine.
