### ISSUE TITLE
issue about badge display

### ISSUE THREAD

**Issue by Pielgrin** [kiwisip/BadgeControl#6]
Hello,
I have an issue about badge display.

When I load my view, the badge display correctly (image 1), but when I leave the screen (for ex: clicking on home button) and get it back, the badge is broken (image 2).

1:
![image](https://user-images.githubusercontent.com/18363758/83332862-ded09c00-a29d-11ea-8f23-659b2bf5aed3.png)

2:
![image](https://user-images.githubusercontent.com/18363758/83332872-eb54f480-a29d-11ea-86c0-e7c24ef3ed36.png)

PS: Thank's for this really useful library

**Comment by rkrenecky** [comment]
Hi! 
Thanks for the submitting the issue. It has now been fixed and new version was [released](https://github.com/kiwisip/BadgeControl/releases/tag/1.2.1) - I hope the library will serve you well!

**Comment by Pielgrin** [comment]
> Thanks for the submitting the issue. It has now been fixed and new version was [released](https://github.com/kiwisip/BadgeControl/releases/tag/1.2.1) - I hope the library will serve you well!

Thank you so much for your quick reply!
